MyWorldAlbum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('login/', user_views.photographer_connect, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('about/', user_views.about, name="about"),

    path('photographers/<str:slug>/', user_views.UserProfileView, name="photographer_home"),
    path('photographers/<str:author_slug>/update/', user_views.profile_update, name="update_profile"),
    path('photographers/<str:author_slug>/update_password/', user_views.change_password, name="update_password"),
    path('', include("album.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'album.views.error_404'

album/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name='album'


urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('pictures/add/', views.PhotoCreateView.as_view(), name="add_photo"),
    path('pictures/<str:author_slug>/<str:slug>-<int:pk>/', views.PhotoDetailView.as_view(), name="detail_photo"),
    path('pictures/<str:author_slug>/<str:slug>-<int:pk>/modify/', views.PhotoUpdateView.as_view(), name="update_photo"),
    path('pictures/<str:author_slug>/<str:slug>-<int:pk>/delete/', views.PhotoDeleteView.as_view(), name="delete_photo"),
    path('pictures/add_comment/', views.AddCommentView, name='add_comment'),
    path('pictures/delete_comment/', views.DeleteCommentView, name='delete_comment'),
    path("search/", views.search_bar_view, name='search_bar'),

]

users/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify
from PIL import Image
import os


def picture_rename(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    return f'profile_pics/profile_pic-{instance.user.username}{file_extension}'#.format(userid= instance.user.id, basename= basefilename, randomstring= randomstr, ext= file_extension)

class Photographer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(default='')
    image = models.ImageField(upload_to=picture_rename, default="default.jpg")


    def __str__(self):
        return f'{self.user.username} Photographer'

    def save(self, *args, **kwargs):
        value = self.user.username
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('photographer_home', args=[
            str(self.slug),
        ])

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.utils.safestring import mark_safe
from .models import Photographer


class UserRegisterForm(UserCreationForm):

    # /!\ the * symbol on labels is from crispy forms and named asteriskField

    username = forms.CharField(label="Username ", help_text="Choose your photographer name")
    email = forms.EmailField(label="Email ")
    password1 = forms.CharField(
        label="Password ",
        widget=forms.PasswordInput,
        help_text=mark_safe("Choose carefully<br>Must contain at least 8 characters<br>Must not be only digits")
    )

    password2 = forms.CharField(
        label="Password confirmation ",
        widget=forms.PasswordInput,
        help_text="Please type again for verification"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class Connection_form(forms.Form):
    username = forms.CharField(label="Username", max_length=30)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Photographer
        fields = ['image']

        widgets = {
          'image': forms.FileInput(attrs={'class': 'color-green'}),
        }


class PasswordUpdateForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Current password ",
        widget=forms.PasswordInput,
        help_text="Enter your current password"
    )
    new_password1 = forms.CharField(
        label="New password ",
        widget=forms.PasswordInput,
        help_text=mark_safe("Choose carefully<br>Must contain at least 8 characters<br>Must not be only digits")
    )
    new_password2 = forms.CharField(
        label="Repeat new password ",
        widget=forms.PasswordInput,
        help_text="Type your new password again"
    )

    def clean(self):
        cleaned_data = super(PasswordUpdateForm, self).clean()
        old_password = cleaned_data.get('old_password')
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if old_password == new_password1:
            raise forms.ValidationError(
                "New password can't be the same as old password"
            )

        if new_password2 != new_password1:
            raise forms.ValidationError(
                "New password confirmation doesn't match"
            )

        return cleaned_data

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import *
from album.models import *
from .models import *



def register(request):
    context = {}
    context["title"] = "Register"
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        context["form"] = form
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("photographer_home", kwargs={'slug':user.photographer.slug}))
            else:
                messages.error(request, f'We are sorry, an error occured')
            # return redirect('/')
    else:
        form = UserRegisterForm()
        context["form"] = form
    return render(request, 'users/register.html', context)


def photographer_connect(request):
    error = False
    title = "Login"
    if request.method == "POST":
        form = Connection_form(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse("photographer_home", kwargs={'slug':user.photographer.slug}))
            else:
                error = True
                messages.error(request, "Wrong username or password")
                return redirect('login')

        else:
            messages.error(request, "Wrong username or password")
            return redirect('login')

    else:
        form = Connection_form()
        return render(request, 'users/login.html', locals())


@login_required
def profile_update(request, author_slug):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        photographer_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.photographer)

        current_image = Photographer.objects.get(pk=request.user.photographer.pk).image#.delete(save=True)
        # print(current_image)
        if user_form.is_valid() and photographer_form.is_valid():
            new_image = request.user.photographer.image
            if new_image and current_image.name != "profile_pics/default.jpg" and current_image.name != "default.jpg":
                current_image.delete(False)

            user_form.save()
            photographer_form.save()
            messages.success(request, f'Your profile has been successfully updated')
            return redirect(reverse("photographer_home", kwargs={'slug':request.user.photographer.slug}))

    else:
        user_form = UserUpdateForm(instance=request.user)
        photographer_form = ProfileUpdateForm(instance=request.user.photographer)

    context = {
        'user_form': user_form,
        'photographer_form': photographer_form,
        'title': 'Update'
    }

    return render(request, 'users/profile_update.html', context)


def UserProfileView(request, slug):
    photographer_info = get_object_or_404(Photographer, slug=slug)
    context = {
        'photographer_info':photographer_info,
        'photos': Photo.objects.filter(author=photographer_info)
    }

    return render(request, 'users/photographer_profile_home.html', context)


def about(request):
    context = {
        "title": "About"
    }

    return render(request, 'users/about.html', context)


@login_required
def UserPasswordUpdate(request, author_slug):

    if request.method == "POST":
        pass_update_form = PasswordUpdateForm(request.POST)

        if pass_update_form.is_valid():
            new_password = pass_update_form.cleaned_data["new_password"]
            old_password = pass_update_form.cleaned_data["old_password"]

            checked = request.user.check_password(old_password)
            if checked:
                request.user.set_password(new_password)
                request.user.save()
                # auto logout after password update, so user has to be logged in again
                update_session_auth_hash(request, request.user)
                messages.success(request, f'Your password has been successfully updated')

                return redirect(reverse("photographer_home", kwargs={'slug':user.photographer.slug}))
            else:
                messages.error(request, f'The given password is incorrect')

    else:
        pass_update_form = PasswordUpdateForm()

    context = {
        'pass_update_form': pass_update_form,
        'title': 'Password update'
    }

    return render(request, 'users/password_update.html', context)


@login_required
def change_password(request, author_slug):
    if request.method == "POST":
        form = PasswordUpdateForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, f'Your password has been successfully updated')
            print("VALID")
            return redirect(reverse("photographer_home", kwargs={'slug':request.user.photographer.slug}))
        else:
            print("INVALID")
            messages.error(request, f'The given password is incorrect')
            return redirect(request.META['HTTP_REFERER'])
    else:
        form = PasswordUpdateForm(user=request.user)

        context = {
            'form': form,
            'title': 'Password update'
        }

        return render(request, 'users/password_update.html', context)

users/templates/users/about.html
{% extends "album/base.html" %}
{% load static %}


{% block content %}

  <div class="about_card">
    <h3> - MyWorldAlbum - </h3>
    <h5>MyWorldAlbum is a website for demonstration purpose only</h5>
    <h5>by <a href="https://audelcroix.com/">Aurélien Delcroix</a></h5>
    <img src="{% static 'site_pictures/album/myworldalbum_default.jpg' %}" alt="MyWorldAlbum icon">
  </div>

{% endblock content %}

users/templates/users/login.html
{% extends "album/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="content-section">
    <form method="POST" action=".">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4 color-blue">Log in</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-blue" type="submit">Login</button>
      </div>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Don't have an account? <a class="ml-2 green-link" href="{% url 'register' %}">Sign In</a>
      </small>
    </div>
  </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "album/base.html" %}

{% block content %}
    <h2 class="color-blue mt-5">You have been successfully logged out</h2>
    <div class="border-top pt-3">
      <small class="text-muted">
        <a class="ml-2 green-link" href="{% url 'login' %}">Log In again</a>
      </small>
    </div>
{% endblock content %}

users/templates/users/password_update.html
{% extends "album/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mainrow">
      <div class="col-sm-12 col-md-4">
        <img class="profile-pic" src="{{ user.photographer.image.url }}" alt="{{ user.username }}'s profile pic">
      </div>

      <div class="col-sm-12 col-md-8 bg-grey author-description">
        <h2 class="color-blue">{{ user.username }}</h2>
        <p class="color-white">{{ user.email }}</p>
      </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom color-blue mb-4">Update password</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="pb-4">
        <small class="text-muted">
          * marks required fields
        </small>
      </div>
      <div class="form-group">
        <button class="btn btn-outline-blue" type="submit">Update</button>
      </div>
    </form>

    <a class="btn btn-outline-grey" href="{% url 'photographer_home' slug=user.photographer.slug %}">Cancel</a>
  </div>
{% endblock content %}

users/templates/users/photographer_profile_home.html
{% extends 'album/base.html' %}

{% load static %}


{% block title %}
MyWorldAlbum - {{ photographer_info.user.username}}
{% endblock %}

{% block content %}

  <div class="row mainrow">
    <div class="col-sm-12 col-md-4">
      <img class="profile-pic" src="{{ photographer_info.image.url }}" alt="{{ photographer_info.user.username }}'s profile pic">
    </div>

    <div class="col-sm-12 col-md-8 bg-grey author-description">

      {% if user.photographer.pk == photographer_info.pk %}
        <h2 class="color-blue">Welcome, {{ user.username }}</h2>

        {% if photos|length > 0 %}
          <p class="color-white">You have published {{ photos|length }} photo{{ photos|pluralize }}</p>
        {% else %}
          <p class="color-white">You haven't shared any picture yet</p>
        {% endif %}

      {% else %}

        <h2 class="color-blue">>You are paying a visit to {{ photographer_info.user.username }}</h2>

        {% if photos|length > 0 %}
          <p class="color-white">This photographer has published {{ photos|length }} photo{{ photos|pluralize }}</p>
        {% else %}
          <p class="color-white">This photographer hasn't shared any picture yet</p>
        {% endif %}

      {% endif %}

    </div>
  </div>

  {% if user.photographer.pk == photographer_info.pk %}
    <div class="commandsRow">
      <a href="{% url 'album:add_photo' %}" class="btn btn-outline-blue mr-2">
        <i class="fas fa-plus"></i> Add picture
      </a>
      <a class="btn btn-outline-grey" href="{% url 'update_profile' photographer_info.slug %}">
        <i class="fas fa-edit"></i> Update profile
      </a>
      <a class="btn btn-outline-green" href="{% url 'update_password' photographer_info.slug %}">
        <i class="fas fa-key"></i> Update password
      </a>
      {% if user.is_superuser %}
        <a class="btn btn-warning" href="admin/users/photographer/{{ photographer_info.pk }}/change/">
          <i class="fas fa-edit"></i> See in admin panel
        </a>
      {% endif %}
    </div>
  {% endif %}


  <div class="resultArea">
    {% if photos|length > 0 %}
      {% for photo in photos %}
        <a href="{% url 'album:detail_photo' author_slug=photo.author.slug slug=photo.slug pk=photo.pk %}">
          <img src="/media/{{ photo.img }}" class="profile-img mx-1 my-2" alt="{{ photo.description }}">
        </a>
      {% endfor %}
    {% else %}

      {% if user.photographer.pk == photographer_info.pk %}
        <h4>You haven't shared any picture yet</h4>
      {% else %}
        <h4>This photographer hasn't shared any picture yet</h4>
      {% endif %}

    {% endif %}
  </div>

{% endblock %}

users/templates/users/profile_update.html
{% extends "album/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mainrow">
      <div class="col-sm-12 col-md-4">
        <img class="profile-pic" src="{{ user.photographer.image.url }}" alt="{{ user.username }}'s profile pic">
      </div>

      <div class="col-sm-12 col-md-8 bg-grey author-description">
        <h2 class="color-blue">{{ user.username }}</h2>
        <p class="color-white">{{ user.email }}</p>
      </div>
    </div>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom color-blue mb-4">Profile info</legend>
        {{ user_form|crispy }}
        {{ photographer_form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-blue" type="submit">Update</button>
      </div>
    </form>

  </div>
{% endblock content %}

users/templates/users/register.html
{% extends "album/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  {% if user.is_authenticated %}
    <br>
    <h3 class="mt-5">You already have an account!</h3>
  {% else %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4 color-blue">Join Today</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="pb-4">
          <small class="text-muted">
            * marks required fields
          </small>
        </div>
        <div class="form-group">
          <button class="btn btn-outline-blue" type="submit">Sign Up</button>
        </div>
      </form>
      <div class="border-top pt-3">
        <small class="text-muted">
          Already have an account? <a class="ml-1 green-link" href="{% url 'login' %}">Log In</a>
        </small>
      </div>
    </div>
  {% endif %}

{% endblock content %}