MyWorldAlbum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('login/', user_views.photographer_connect, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('about/', user_views.about, name="about"),

    path('photographers/<str:slug>/', user_views.UserProfileView, name="photographer_home"),
    path('photographers/<str:author_slug>/update/', user_views.profile_update, name="update_profile"),
    path('photographers/<str:author_slug>/update_password/', user_views.change_password, name="update_password"),
    path('', include("album.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'album.views.error_404'

album/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name='album'


urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('pictures/add/', views.PhotoCreateView.as_view(), name="add_photo"),
    path('pictures/<str:author_slug>/<str:slug>-<int:pk>/', views.PhotoDetailView.as_view(), name="detail_photo"),
    path('pictures/<str:author_slug>/<str:slug>-<int:pk>/modify/', views.PhotoUpdateView.as_view(), name="update_photo"),
    path('pictures/<str:author_slug>/<str:slug>-<int:pk>/delete/', views.PhotoDeleteView.as_view(), name="delete_photo"),
    path('pictures/add_comment/', views.AddCommentView, name='add_comment'),
    path('pictures/delete_comment/', views.DeleteCommentView, name='delete_comment'),
    path("search/", views.search_bar_view, name='search_bar'),

]

album/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.text import slugify
from users.models import Photographer
from PIL import Image

import uuid
import os


def photo_rename(instance, filename):
    uniqid = str(uuid.uuid1())
    basefilename, file_extension = os.path.splitext(filename)
    return f'album/user_images/{uniqid}-{instance.slug}{file_extension}'


class Photo(models.Model):
    categories = [
        ("animal", "animal"),
        ("art", "art"),
        ("landscape", "landscape"),
        ("nature", "nature"),
        ("people", "people"),
        ("sky", "sky"),
    ]

    title = models.CharField(max_length=128, verbose_name='Title')
    description = models.TextField(max_length=6000, verbose_name='Description')
    category = models.CharField(max_length=16, choices=categories, default="art", verbose_name='Category')
    img = models.ImageField(upload_to=photo_rename)
    author = models.ForeignKey('users.Photographer', on_delete=models.CASCADE)

    slug = models.SlugField(default='', editable=False)

    date_posted = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        value = self.title
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('album:detail_photo', args=[
            str(self.author.slug),
            str(self.slug),
            int(self.pk),
        ])


class Comment(models.Model):
    content = models.TextField(max_length=1000, verbose_name='Content')
    author = models.ForeignKey('users.Photographer', on_delete=models.CASCADE)
    article = models.ForeignKey('Photo', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content[:40]

album/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from datetime import datetime

import os

from .models import *


def error_404(request, exception):
    context = {"title": "Not found"}
    return render(request,'album/404.html', context)

def homepage(request):

    photos = Photo.objects.all().order_by('?')[:3]
    context = {
        "photos": photos
    }
    return render(request, 'album/index.html', context)


class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ["title", 'description', "category", "img"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "New Picture"
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user.photographer
        return super().form_valid(form)

    def get_success_url(self):

        return reverse_lazy("album:detail_photo", kwargs={
            'pk':self.object.pk,
            'slug':self.object.slug,
            'author_slug':self.request.user.photographer.slug
            })


class PhotoUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView): #attention, l'ordre des class importe!!!!
    model = Photo
    fields = ["title", 'description', "category"]
    template_name = "album/photo_update.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update"
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user.photographer
        return super().form_valid(form)

    def test_func(self):
        photo = self.get_object()
        if self.request.user.photographer == photo.author:
            return True
        else:
            return False

    def get_success_url(self):
        photo = self.get_object()
        return reverse_lazy("album:detail_photo", kwargs={
            'pk':photo.pk,
            'slug':photo.slug,
            'author_slug':photo.author.slug,
            })


class PhotoDetailView(DetailView):
    model = Photo
    context_object_name = "photo_info"
    template_name = "album/photo_detail.html"

    def get_context_data(self, **kwargs):

        context = super(PhotoDetailView, self).get_context_data(**kwargs)
        page = self.request.GET.get('page')
        comments = Paginator(self.object.comment_set.all().order_by("-date_posted"), 5)
        context['comments'] = comments.get_page(page)
        context['comments_number'] = self.object.comment_set.count()

        #check if picture file exists
        if os.path.isfile("."+self.object.img.url):
            context['allowed'] = True
        else:
            context['allowed'] = False
        #print("."+self.object.img.url)

        # for the page title
        photo = self.get_object()
        context['title'] = photo.title

        return context


class PhotoDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Photo
    # gen template name = photo_confirm_delete

    def test_func(self):
        photo = self.get_object()
        if self.request.user.photographer == photo.author:
            return True
        else:
            return False

    def get_success_url(self):
        return reverse_lazy("photographer_home", kwargs={'slug':self.request.user.photographer.slug,})


def search_bar_view(request):
    context = {}
    context['photos'] = ""
    queryset = []

    if request.GET:
        query = request.GET['q']
        context['query'] = str(query) # pour l'expo dans le template

        queries = query.split(" ")
        for q in queries:
            photos = Photo.objects.filter(
                Q(title__icontains=q) |
                Q(description__icontains=q) |
                Q(category__icontains=q)
            ).distinct()

            for photo in photos:
                queryset.append(photo)

        context['photos'] = queryset
        context['title'] = str(query)

    return render(request, "album/search_results.html", context)



def AddCommentView(request):
    print("ajax departure")
    if request.method == 'POST':

        response_data = {}
        response_data['permission'] = False

        try:
            if request.POST.get("photoId"):
                clean_img_id = int(request.POST.get("photoId"))
                photo_id = request.POST.get("photoId")
            else:
                return JsonResponse(response_data)
        except ValueError:
            return JsonResponse(response_data)

        try:
            commented_photo = Photo.objects.get(pk=photo_id)
            content_text = request.POST.get('content')
            comment = Comment(content=content_text, author=request.user.photographer, article=commented_photo)
            comment.save()

            response_data['permission'] = True
            response_data['report'] = "{} has commented: {}".format(request.user.photographer.pk, content_text)
            response_data['userImg'] = str(request.user.photographer.image)
            response_data['username'] = str(request.user.username)
            response_data['newCommentId'] = comment.pk

            date_cur = datetime.now()
            response_data['date'] = date_cur.strftime("%m/%d, %H:%M")

            return JsonResponse(response_data)
        except Photo.DoesNotExist:
            return JsonResponse(response_data)

    else:
        return HttpResponse(
            "error"
        )


def DeleteCommentView(request):

    response_data = {}
    response_data["permission"] = False

    if request.POST.get("targetCommentId") and request.POST.get("photoId"):

        try:
            cleaned_commentId = int(request.POST.get("targetCommentId"))
            cleaned_photoId = int(request.POST.get("photoId"))
        except ValueError:
            return JsonResponse(response_data)

        try:
            photo = Photo.objects.get(pk=cleaned_photoId)
            comment = Comment.objects.get(pk=cleaned_commentId)
            photographer = request.user.photographer

            if comment.article != photo or (comment.author != photographer and photo.author != photographer):
                return JsonResponse(response_data)

            else:
                response_data["permission"] = True
                comment.delete()
                return JsonResponse(response_data)

        except Photo.DoesNotExist:
            return JsonResponse(response_data)

        except Comment.DoesNotExist:
            return JsonResponse(response_data)

    else:
        return JsonResponse(response_data)

album/templates/album/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{% static 'css/album/main.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/album/master.css' %}">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

  <link rel="shortcut icon" type="image/png" href="{% static 'site_pictures/album/myworldalbum_favicon.png' %}"/>

  <script src="{% static 'js/album/search_controls.js' %}"></script>

  {% if title %}
  <title>MyWorldAlbum - {{ title }}</title>
  {% else %}
  <title>MyWorldAlbum</title>
  {% endif %}

</head>

<body>
  <header class="">
    <nav class="navbar navbar-expand-lg">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar" aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="main-navbar">

        <a class="navbar-brand ml-2 mr-4" href="{% url 'album:homepage' %}">MyWorldAlbum</a>

        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'album:homepage' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-item nav-link" href="https://audelcroix.com/">Portfolio</a>
          </li>

          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              Categories
            </a>
            <div class="dropdown-menu bg-grey">
              <a class="dropdown-item color-blue" href="/search/?q=animal">Animal</a>
              <a class="dropdown-item color-blue" href="/search/?q=art">Art</a>
              <a class="dropdown-item color-blue" href="/search/?q=landscape">Landscape</a>
              <a class="dropdown-item color-blue" href="/search/?q=nature">Nature</a>
              <a class="dropdown-item color-blue" href="/search/?q=people">People</a>
              <a class="dropdown-item color-blue" href="/search/?q=sky">Sky</a>
            </div>
          </li>

          <li class="nav-item">
            <button class="btn search-trigger" name="button" onclick="open_searchbar()"><i class="fas fa-search fa-lg"></i></button>
          </li>

        </ul>

        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'album:add_photo' %}">New Picture</a>
          <a class="nav-item nav-link" href="{% url 'photographer_home' slug=user.photographer.slug %}">Profile</a>
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
          {% endif %}
        </div>

      </div>

    </nav>
  </header>

  <main role="main" class="container">

    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} {% if message.tags == "error" %}alert-danger{% endif %}">
        {{ message }}
      </div>
      {% endfor %}
    {% endif %}

    {% block content %}

    {% endblock %}

  </main>

  <div id="search-modal" class="overlay">
    <span class="closebtn" onclick="close_searchbar()" title="Close Search-bar">×</span>
    <div class="overlay-content">
      <form action="{% url 'album:search_bar' %}" class="form-inline" method="GET">
        <div class="input-container">
          <input id="searchbar-field" type="text" placeholder="Explore the community's pictures!" name="q">
          <button type="submit"><i class="fa fa-search fa-lg"></i></button>
        </div>
      </form>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  {% block scriptblock %}
  {% endblock %}
</body>

</html>

album/templates/album/explore_category.html
{% extends 'album/base.html' %}
{% load bootstrap4 %}

{% block title %}
MyWorldAlbum - {{ display_category }}
{% endblock %}

{% block bodyblock %}


  <div class="resultArea">
    {% if photos|length > 0 %}
      {% for photo in photos %}
      <a href="{% url 'album:photo_detail' pk=photo.pk %}">
        <img src="/media/{{ photo.img }}" class="result-floater profile-img mx-1 my-2" alt="{{ photo.title }}, by {{ photo.author }}">
      </a>
      {% endfor %}
    {% else %}
      <h4>This category is empty!</h4><br>
      <h4>Why not share your own pictures?</h4>
    {% endif %}
  </div>

  <div class="sqdqsd">
    ssdsd
  </div>

  <div class="sqdqsd">
    ssdsd
  </div>

  <div class="commentPaginationArea">
    {% if page_obj.has_other_pages %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="not-square mr-2"><a href="?page=1">first</a></li>
          <li class="not-square mr-1"><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled not-square"><span>&laquo;</span></li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="not-square ml-1"><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
          <li class="not-square ml-2"><a href="?page={{ page_obj.paginator.num_pages }}">last</a></li>

        {% endif %}
      </ul>
    {% endif %}
  </div>

{% endblock %}

album/templates/album/index.html
{% extends "album/base.html" %}

{% block content %}
  <div class="row my-5 flex-column-reverse flex-md-row">

    <div class="col-md-8">
      <div id="indexCarousel" class="carousel slide" data-ride="carousel">


        <ul class="carousel-indicators">
          <li data-target="#indexCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#indexCarousel" data-slide-to="1"></li>
          <li data-target="#indexCarousel" data-slide-to="2"></li>
        </ul>


        <div class="carousel-inner">
          {% for photo in photos %}
          <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
            <a href="{% url 'album:detail_photo' author_slug=photo.author.slug slug=photo.slug pk=photo.pk %}">
              <img src="media/{{ photo.img }}" class="carousel-demo-img" alt="{{ photo.title }}">
            </a>
          </div>
          {% endfor %}
        </div>


        <a class="carousel-control-prev" href="#indexCarousel" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#indexCarousel" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>

      </div>

    </div>

    <div class="col-md-4 bg-grey">
      <h1 class="text-center color-blue">- Welcome to -</h1>
      <h1 class="text-center color-blue">MyWorldAlbum</h1>
      <hr class="bg-green">
      <h5 class="color-white">A website dedicated to sharing photos and pictures!</h5>
      <h5 class="color-white">Share your art with the community today!</h5>
    </div>

  </div>
{% endblock %}

album/templates/album/photo_confirm_delete.html
{% extends "album/base.html" %}

{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Picture?</legend>
        <h2>Are you sure you want to delete "{{ object.title }}" ?</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger" type="submit">Delete</button>
        <a class="btn btn-outline-secondary" href="{% url 'album:homepage' %}">Cancel</a>
      </div>
    </form>
  </div>
{% endblock content %}

album/templates/album/photo_detail.html
{% extends 'album/base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}

  {% if allowed %}
    <div class="img-container">
      <img src="{{ photo_info.img.url }}" class="img-responsive displayed-img" alt="{{ photo_info.title }}, by {{ photo_info.author }}">
    </div>
  {% else %}
    <div class="img-load-error">
      <h5>We are sorry, this image is unaccessible</h5>
    </div>
  {% endif %}

  <div class="photo-description bg-grey">
    <div class="row no-gutters">
      <div class="col-md-2 col-sm-0 profile-pic-area">
        <a href="{% url 'photographer_home' slug=photo_info.author.slug %}">
          <img src="{{ photo_info.author.image.url }}" class='authorProfilePic' alt="{{ comment.author }}" title="By {{ photo_info.author }}">
        </a>
      </div>

      <div class="col-md-10 col-sm-12 description-area color-white">
        <h5 class="pt-2 color-blue">{{ photo_info.title }}</h5>
        <h6>
          By <a href="{% url 'photographer_home' slug=photo_info.author.slug %}" class="green-link">{{ photo_info.author.user.username }}</a> in <a class="green-link" href="/search/?q={{ photo_info.category }}">{{ photo_info.category }}</a>
          - posted {{ photo_info.date_posted|date:"l d F Y" }}
        </h6>
        <p>{{ photo_info.description }}</p>

        {% if photo_info.author.pk == user.photographer.pk or user.is_superuser %}
          <button type="button" class="btn btn-outline-danger mb-1" data-toggle="modal" data-target="#deleteModal" title="Delete this picture">
            <i class="far fa-trash-alt fa-lg"></i>
          </button>
          <a href="{% url 'album:update_photo' author_slug=photo_info.author.slug slug=photo_info.slug pk=photo_info.pk %}">
            <button type="button" class="btn btn-outline-blue mb-1" title="Edit this picture">
              <i class="fas fa-pencil-alt fa-lg"></i>
            </button>
          </a>
          {% if user.is_superuser %}
            <a href="/admin/album/photo/{{ photo_info.pk }}/change/">
              <button type="button" class="btn btn-warning mb-1" title="See in admin panel">
                <i class="fas fa-crown fa-lg"></i>
              </button>
            </a>
          {% endif %}
        {% endif %}

      </div>
    </div>
  </div>

  <div class="error-zone my-2">
    <p class="error-target"></p>
  </div>

  <div class="commentFormArea">
    {% if user.is_authenticated %}
    <h5>Add your comment</h5>
    <textarea class="form-control mb-2" id="commentFormTextarea" form="commentFormEXP" rows="4" cols="50" placeholder="Your comment" id='commentTextArea' required></textarea>
    <form class="" id='commentFormEXP' action="{% url 'album:add_comment' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" id="photoId" value="{{ photo_info.pk }}">
      <button type="submit" class="btn btn-outline-blue">Add comment</button>
    </form>
    {% else %}
      <h5>You must be authenticated to post comments</h5>
    {% endif %}
  </div>


  <div id="comment-zone">
    {% for comment in comments %}
      <div class="comment-area bg-grey" data-commentId="{{ comment.pk }}">
        <div class="row no-gutters">
          <div class="col-md-2 col-sm-0 profile-pic-area">
            <img src="{{ comment.author.image.url }}" class='commentProfilePic' alt="{{ comment.author }}">
          </div>

          <div class="col-md-10 col-sm-12 description-area">

            <h6 class="pt-1 color-green">
              {{ comment.author.user.username }} said:
              {% if photo_info.author.pk == user.photographer.pk or comment.author.pk == user.photographer.pk  %}
                <a class="text-danger commentDeleteTrigger float-right mr-2 mt-1"><i class="far fa-trash-alt fa-lg"></i></a>
              {% endif %}
              <small class="float-right mr-2 mt-1">{{ comment.date_posted|date:"m/d, G:i" }}</small>
            </h6>
            <p class="color-white">{{ comment.content }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>


  <div class="commentPaginationArea mb-2">
    {% if comments.has_other_pages %}
      <ul class="pagination">
        {% if comments.has_previous %}
          <li class="not-square mr-2"><a href="?page=1">first</a></li>
          <li class="not-square mr-1"><a href="?page={{ comments.previous_page_number }}" id="previous-page">&laquo;</a></li>

        {% endif %}
        {% for i in comments.paginator.page_range %}
          {% if comments.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li class="joinable-page"><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if comments.has_next %}
          <li class="not-square ml-1"><a href="?page={{ comments.next_page_number }}" id="next-page">&raquo;</a></li>
          <li class="not-square ml-2"><a href="?page={{ comments.paginator.num_pages }}">last</a></li>

        {% endif %}
      </ul>
    {% endif %}
  </div>


  <!-- Modal -->
  {% if photo_info.author.pk == user.photographer.pk %}
    <div class="modal fade" id="deleteModal">
      <div class="modal-dialog">
        <div class="modal-content bg-grey">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title color-blue">Delete this picture?</h4>
            <button type="button" class="close green-link" data-dismiss="modal">&times;</button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">
            <a href="{% url 'album:delete_photo' author_slug=photo_info.author.slug slug=photo_info.slug pk=photo_info.pk %}">
              <button type="button" class="btn btn-danger">Delete</button>
            </a>
          </div>

        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}



{% block scriptblock %}
  <script src="{% static 'js/album/ajax.js' %}"></script>
  <script src="{% static 'js/album/pagination_by_keyboard.js' %}"></script>
{% endblock %}

album/templates/album/photo_form.html
{% extends "album/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4 color-blue">Add picture</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-blue" type="submit">Publish</button>
        </div>
      </form>
    </div>
{% endblock content %}

album/templates/album/photo_update.html
{% extends "album/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Modify picture</legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-outline-primary" type="submit">Modify</button>
        </div>
      </form>
    </div>
{% endblock content %}

album/templates/album/search_results.html
{% extends 'album/base.html' %}

{% load static %}


{% block title %}
Results - {{ query }}
{% endblock %}

{% block content %}


  {% if photos|length > 0 %}
    {% for photo in photos %}
      <!-- <a href="{% url 'album:detail_photo' author_slug=photo.author.slug slug=photo.slug pk=photo.pk %}">
        <img src="/media/{{ photo.img }}" class="float-left search-result-img mx-1 my-2" alt="{{ photo.description }}">
      </a> -->
      <div class="tooltipme">
        <a href="{% url 'album:detail_photo' author_slug=photo.author.slug slug=photo.slug pk=photo.pk %}">
          <img src="/media/{{ photo.img }}" class="float-left search-result-img mx-1 my-2" alt="{{ photo.description }}">
        </a>
        <span class="tooltiptext">{{ photo.title }}</span>
      </div>
    {% endfor %}
  {% else %}
    <h4>No result for {{ query }}</h4>
  {% endif %}


{% endblock %}